SistemaVenda/Models/ProdutoViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaVenda.Models
{
    public class ProdutoViewModel
    {
        public int? Codigo { get; set; }

        [Required(ErrorMessage = "Informe a Descrição do produto!")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "Informe a Quantidade em Estoque do produto!")]
        public double Quantidade { get; set; }

        [Required(ErrorMessage = "Informe o Valor unitário do Produto!")]
        [Range(0.1, Double.PositiveInfinity)]
        public decimal? Valor { get; set; }

        [Required(ErrorMessage = "Informe a Categoria do Produto!")]
        public int? CodigoCategoria { get; set; }

        public IEnumerable<SelectListItem> ListaCategorias { get; set; }

        public string DescricaoCategoria { get; set; }
        public int? CodigoUsuario { get; set; }
    }
}

SistemaVenda/Controllers/CategoriaController.cs
using Aplicacao.Controllers;
using Aplicacao.Helpers;
using Aplicacao.Servico.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaVenda.Helpers;
using SistemaVenda.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaVenda.Controllers
{
    public class CategoriaController : MensagemController
    {
        private readonly IServicoAplicacaoCategoria ServicoAplicacaoCategoria;

        public CategoriaController(IServicoAplicacaoCategoria ServicoAplicacaoCategoria)
        {
            this.ServicoAplicacaoCategoria = ServicoAplicacaoCategoria;
        }

        public IActionResult Index()
        {
            return View(ServicoAplicacaoCategoria.Listagem((int)HttpContext.Session.GetInt32(Sessao.CodigoUsuario)));
        }

        [HttpGet]
        public IActionResult Cadastro(int? id)
        {
            CategoriaViewModel viewModel = ServicoAplicacaoCategoria.CarregarRegistro(id is null? 0 :(int)id);
            
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Cadastro(CategoriaViewModel entidade)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    entidade.CodigoUsuario = HttpContext.Session.GetInt32(Sessao.CodigoUsuario);
                    ServicoAplicacaoCategoria.Cadastrar(entidade);

                    if (entidade.Codigo != 0 && entidade.Codigo != null)
                    {
                        MensagemSucesso("Categoria editada com sucesso.");
                    }
                    else
                    {
                        MensagemSucesso("Categoria cadastrada com sucesso.");
                    }
                }
                catch (MensagemErroException ex)
                {
                    MensagemErro(ex.Message);
                }
                catch (Exception ex)
                {
                    MensagemErro("Erro ao cadastrar categoria.");
                }
            }
            else
            {
                MensagemErro("Necessário preencher todos os campos obrigatórios.");
                return View(entidade);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Deletar(int? id)
        {
            CategoriaViewModel viewModel = ServicoAplicacaoCategoria.CarregarRegistro(id is null ? 0 : (int)id);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Deletar(int id)
        {
            try
            {
                ServicoAplicacaoCategoria.Excluir(id);
                MensagemSucesso("Categoria deletada com sucesso.");
            }
            catch (MensagemErroException ex)
            {
                MensagemErro(ex.Message);
            }
            catch (Exception ex)
            {
                MensagemErro("Erro ao deletar categoria.");
            }

            return RedirectToAction("Index");
        }
    }
}

SistemaVenda/Controllers/ProdutoController.cs
using Aplicacao.Servico.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaVenda.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using SistemaVenda.Helpers;
using Aplicacao.Controllers;
using Aplicacao.Helpers;

namespace SistemaVenda.Controllers
{
    public class ProdutoController : MensagemController
    {
        private readonly IServicoAplicacaoProduto ServicoAplicacaoProduto;
        private readonly IServicoAplicacaoCategoria ServicoAplicacaoCategoria;

        public ProdutoController(IServicoAplicacaoProduto ServicoAplicacaoProduto, IServicoAplicacaoCategoria ServicoAplicacaoCategoria)
        {
            this.ServicoAplicacaoProduto = ServicoAplicacaoProduto;
            this.ServicoAplicacaoCategoria = ServicoAplicacaoCategoria;
        }

        public IActionResult Index()
        {
            return View(ServicoAplicacaoProduto.Listagem((int)HttpContext.Session.GetInt32(Sessao.CodigoUsuario)));
        }

        [HttpGet]
        public IActionResult Cadastro(int? id)
        {
            var viewModel = ServicoAplicacaoProduto.CarregarRegistro(id is null? 0: (int)id);
            viewModel.ListaCategorias = ServicoAplicacaoCategoria.ListagemSelectList((int)HttpContext.Session.GetInt32(Sessao.CodigoUsuario));

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Cadastro(ProdutoViewModel entidade)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    entidade.CodigoUsuario = HttpContext.Session.GetInt32(Sessao.CodigoUsuario);
                    ServicoAplicacaoProduto.Cadastrar(entidade);

                    if (entidade.Codigo != 0 && entidade.Codigo != null)
                    {
                        MensagemSucesso("Produto editado com sucesso.");
                    }
                    else
                    {
                        MensagemSucesso("Produto cadastrado com sucesso.");
                    }
                }
                catch (MensagemErroException ex)
                {
                    MensagemErro(ex.Message);
                }
                catch (Exception ex)
                {
                    MensagemErro("Erro ao cadastrar produto.");
                }
            }
            else
            {
                entidade.ListaCategorias = ServicoAplicacaoCategoria.ListagemSelectList((int)HttpContext.Session.GetInt32(Sessao.CodigoUsuario));
                MensagemErro("Necessário preencher todos os campos obrigatórios.");
                return View(entidade);
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Deletar(int? id)
        {
            var viewModel = ServicoAplicacaoProduto.CarregarRegistro(id is null ? 0 : (int)id);
            viewModel.ListaCategorias = ServicoAplicacaoCategoria.ListagemSelectList((int)HttpContext.Session.GetInt32(Sessao.CodigoUsuario));

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Deletar(int id)
        {
            try
            {
                ServicoAplicacaoProduto.Excluir(id);
                MensagemSucesso("Produto deletado com sucesso.");
            }
            catch (MensagemErroException ex)
            {
                MensagemErro(ex.Message);
            }
            catch (Exception ex)
            {
                MensagemErro("Erro ao deletar produto.");
            }

            return RedirectToAction("Index");
        }
    }
}

SistemaVenda/Views/Produto/Cadastro.cshtml
@model SistemaVenda.Models.ProdutoViewModel;

@{
    ViewData["Title"] = "Produto";
}
<h2>Produto</h2>
<hr />

<form asp-controller="Produto" asp-action="Cadastro" method="post">
    <input type="hidden" asp-for="Codigo" value="@Model.Codigo" />
    <div class="form-group">
        <div class="col-4">
            <label>Descricao</label>
            <input type="text" asp-for="Descricao" value="@Model.Descricao" class="form-control" />
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>

    </div>
    <div class="form-group">
        <div class="col-4">
            <label>Quantidade</label>
            <input type="number" asp-for="Quantidade" value="@Model.Quantidade" class="form-control" />
            <span asp-validation-for="Quantidade" class="text-danger"></span>
        </div>

    </div>
    <div class="form-group">
        <div class="col-4">
            <label>Valor</label>
            <input type="text" asp-for="Valor" value="@Model.Valor" class="form-control" />
            <span asp-validation-for="Valor" class="text-danger"></span>
        </div>

    </div>
    <div class="form-group">
        <div class="col-12 row">
            <div class="col-4">
                <label>Categoria</label>
                <select asp-for="CodigoCategoria" class="form-control input-group-lg" asp-items="@Model.ListaCategorias"></select>
                <span asp-validation-for="CodigoCategoria" class="text-danger"></span>
            </div>
            <div class="col-2">
                <a href="@Url.Action("Cadastro","Categoria")" style="top: 24px; position: relative;" class="btn btn-success">Nova Categoria</a>
            </div>
        </div>
    </div>
    <br />
    <div class="col">
        <button type="submit" class="btn btn-success">Gravar</button>
    </div>
</form>

SistemaVenda/Views/Produto/Deletar.cshtml
@model SistemaVenda.Models.ProdutoViewModel;

@{
    ViewData["Title"] = "Produto";
}
<h2>Produto</h2>
<hr />

<form asp-controller="Produto" asp-action="Deletar" method="post">
    <input type="hidden" asp-for="Codigo" value="@Model.Codigo" />
    <div class="form-group">
        <div class="col-4">
            <label>Descricao</label>
            <input type="text" asp-for="Descricao" value="@Model.Descricao" disabled class="form-control" />
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>

    </div>
    <div class="form-group">
        <div class="col-4">
            <label>Quantidade</label>
            <input type="number" asp-for="Quantidade" value="@Model.Quantidade" disabled class="form-control" />
            <span asp-validation-for="Quantidade" class="text-danger"></span>
        </div>

    </div>
    <div class="form-group">
        <div class="col-4">
            <label>Valor</label>
            <input type="text" asp-for="Valor" value="@Model.Valor" disabled class="form-control" />
            <span asp-validation-for="Valor" class="text-danger"></span>
        </div>

    </div>
    <div class="form-group">
        <div class="col-4">
            <label>Categoria</label>
            <select asp-for="CodigoCategoria" class="form-control input-group-lg" disabled asp-items="@Model.ListaCategorias"></select>
            <span asp-validation-for="CodigoCategoria" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="col">
        <button type="submit" class="btn btn-danger">Deletar</button>
    </div>
</form>

SistemaVenda/Views/Produto/Index.cshtml
@model List<SistemaVenda.Models.ProdutoViewModel>;

@{
    ViewData["Title"] = "Produtos";
}
<link href="~/css/Grid/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="~/css/Grid/responsive.bootstrap4.min.css" rel="stylesheet" />
<link href="~/css/Grid/buttons.bootstrap4.min.css" rel="stylesheet" />
<link href="~/css/Grid/Colors.css" rel="stylesheet" />

<ol class="breadcrumb float-xl-right">
    <li class="breadcrumb-item text-dark-blue"><a href="@Url.Action("Index","Home")">Página principal</a></li>
    <li class="breadcrumb-item active text-dark-blue opacity-75">Listagem de Produtos</li>
</ol>
<h1 class="page-header text-dark-blue">Listagem de Produtos<small></small></h1>

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Produtos</h4>
    </div>
    <div class="panel-body">
        <div class="col-md-12">&nbsp;</div>
        <div class="col-md-12 row">
            <div class="col-md-10">

            </div>
            <div class="col-md-2">
                <input type="button" class="btn btn-primary float-right" onclick="Cadastrar()" value="Cadastrar"/>
            </div>
        </div>
        <div class="col-md-12">
            &nbsp;
        </div>
        <div class="col-md-12 row">
            <div class="col-md-12">
                <table id="data-table-default" class="table table-striped table-bordered align-middle">
                    <thead>
                        <tr>
                            <th style="width:115px">
                                Ações
                            </th>
                            <th>Código</th>
                            <th>Descrição</th>
                            <th>Quantidade</th>
                            <th>Valor</th>
                            <th>Categoria</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td><input type="button" class="btn btn-success" onclick="Editar(@item.Codigo)" value="Editar"/>&nbsp;<input type="button" class="btn btn-danger" onclick="Deletar(@item.Codigo)" value="Deletar"/></td>
                                <td>
                                    @item.Codigo
                                </td>
                                <td>
                                    @item.Descricao
                                </td>
                                <td>
                                    @item.Quantidade
                                </td>
                                <td>
                                    @item.Valor
                                </td>
                                <td>
                                    @item.DescricaoCategoria
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>

<script src="~/js/Grid/jquery.dataTables.min.js"></script>
<script src="~/js/Grid/dataTables.bootstrap4.min.js"></script>
<script src="~/js/Grid/dataTables.responsive.min.js"></script>
<script src="~/js/Grid/dataTables.bootstrap4.min.js"></script>
<script src="~/js/Grid/dataTables.buttons.min.js"></script>
<script src="~/js/Grid/buttons.bootstrap4.min.js"></script>
<script src="~/js/Grid/buttons.colVis.min.js"></script>
<script src="~/js/Grid/buttons.flash.min.js"></script>
<script src="~/js/Grid/buttons.html5.min.js"></script>
<script src="~/js/Grid/buttons.print.min.js"></script>
<script src="~/js/Grid/pdfmake.min.js"></script>
<script src="~/js/Grid/vfs_fonts.js"></script>
<script src="~/js/Grid/jszip.min.js"></script>

<script>
    var options = {
        dom: '<"dataTables_wrapper dt-bootstrap"<"row"<"col-xl-7 d-block d-sm-flex d-xl-block justify-content-center"<"d-block d-lg-inline-flex me-0 me-md-3 float-right"l><"d-block d-lg-inline-flex"B>><"col-xl-5 d-flex d-xl-block justify-content-center"fr>>t<"row"<"col-md-5"i><"col-md-7"p>>>',
        buttons: [
            { extend: 'copy', className: 'btn-sm' },
            { extend: 'csv', className: 'btn-sm' },
            { extend: 'excel', className: 'btn-sm' },
            { extend: 'pdf', className: 'btn-sm' },
            { extend: 'print', className: 'btn-sm' }
        ],
        retrieve: true,
        responsive: true,
        colReorder: true,
        keys: true,
        rowReorder: true,
        select: true
    };

    if ($(window).width() <= 767) {
        options.rowReorder = false;
        options.colReorder = false;
    }
    $('#data-table-default').DataTable(options);

    function Editar(Codigo) {
        window.location = window.origin + "\\Produto\\Cadastro\\" + Codigo;
    }

    function Cadastrar() {
        window.location = window.origin + "\\Produto\\Cadastro";
    }

    function Deletar(Codigo) {
        window.location = window.origin + "\\Produto\\Deletar\\" + Codigo;
    }
</script>